### ISSUE TITLE
你的源码可以把log4j改成slf4j么？

### ISSUE THREAD

**Issue by ShisanXing** [wxiaoqi/ace-cache#9]
我项目是logback，不想说再引入一个log4j

**Comment by ShisanXing** [comment]
我在我本地改了一份slf4j的，而且改为lombok模式的在用，希望作者能将代码修正一下，不一定所有人的项目都喜欢log4j

**Comment by wxiaoqi** [comment]
可以PR上来

**Comment by ShisanXing** [comment]
> 可以PR上来

码主可以新建dev分支什么的，就一个master分支
